image: therickys93/ubuntu14swiftenv

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y openssl libssl-dev software-properties-common python-software-properties apt-transport-https
          - swiftenv install 3.1
          - swiftenv global 3.1
          - swift build
          - swift test